#!/usr/bin/env python3
"""Parse sweep CSVs and generate LaTeX tables in docs/tables.tex."""

import csv
from collections import defaultdict
from pathlib import Path

OUT = Path("docs/tables.tex")
SOR_CSV = Path("output/sweep_eta_omega.csv")
RBGS_CSV = Path("output/sweep_rbgs.csv")


def read_sor():
    rows = []
    with open(SOR_CSV) as f:
        for r in csv.DictReader(f):
            rows.append({
                "eta": float(r["eta"]),
                "omega": float(r["omega"]),
                "iters": int(r["total_iters"]),
                "time": float(r["total_time_ms"]),
            })
    return rows


def read_rbgs():
    rows = []
    with open(RBGS_CSV) as f:
        for r in csv.DictReader(f):
            rows.append({
                "eta": float(r["eta"]),
                "iters": int(r["total_iters"]),
                "time": float(r["total_time_ms"]),
            })
    return rows


def table_eta_omega(sor_data):
    """Table 1: eta × omega grid of total iterations."""
    etas = sorted(set(r["eta"] for r in sor_data))
    omegas = sorted(set(r["omega"] for r in sor_data))

    lookup = {}
    for r in sor_data:
        lookup[(r["eta"], r["omega"])] = r["iters"]

    # Find best omega per eta
    best = {}
    for eta in etas:
        best[eta] = min(omegas, key=lambda w: lookup.get((eta, w), float("inf")))

    ncols = len(omegas)
    col_spec = "r" + "r" * ncols
    lines = [
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Total SOR iterations (200 DLA growth steps, $N=100$) for each $(\eta, \omega)$ combination. "
        r"Best $\omega$ per $\eta$ is \textbf{bold}.}",
        r"\label{tab:eta-omega}",
        rf"\begin{{tabular}}{{{col_spec}}}",
        r"\toprule",
    ]
    header = r"$\eta$ \textbackslash\ $\omega$"
    for w in omegas:
        header += rf" & {w:.2f}"
    header += r" \\"
    lines.append(header)
    lines.append(r"\midrule")

    for eta in etas:
        row = f"{eta:.1f}"
        for w in omegas:
            val = lookup.get((eta, w), "---")
            if w == best[eta]:
                row += rf" & \textbf{{{val}}}"
            else:
                row += rf" & {val}"
        row += r" \\"
        lines.append(row)

    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines)


def table_comparison(sor_data, rbgs_data):
    """Table 2: SOR (best omega) vs RB-GS per eta."""
    etas = sorted(set(r["eta"] for r in sor_data))

    # Best SOR per eta
    best_sor = {}
    for eta in etas:
        candidates = [r for r in sor_data if r["eta"] == eta]
        best_sor[eta] = min(candidates, key=lambda r: r["iters"])

    rbgs_by_eta = {r["eta"]: r for r in rbgs_data}

    lines = [
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Comparison of SOR (best $\omega$) vs Red-Black Gauss-Seidel. "
        r"200 DLA growth steps, $N=100$.}",
        r"\label{tab:sor-vs-rbgs}",
        r"\begin{tabular}{rrrrrr}",
        r"\toprule",
        r"$\eta$ & Best $\omega$ & SOR iters & SOR time (ms) & RBGS iters & RBGS time (ms) \\",
        r"\midrule",
    ]

    for eta in etas:
        s = best_sor[eta]
        rb = rbgs_by_eta.get(eta, {"iters": "---", "time": "---"})
        lines.append(
            f"{eta:.1f} & {s['omega']:.2f} & {s['iters']} & {s['time']:.1f}"
            f" & {rb['iters']} & {rb['time']:.1f} \\\\"
        )

    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines)


def main():
    sor_data = read_sor()
    rbgs_data = read_rbgs()

    t1 = table_eta_omega(sor_data)
    t2 = table_comparison(sor_data, rbgs_data)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w") as f:
        f.write("% Auto-generated by scripts/generate_tables.py\n")
        f.write("% Include in your report with: \\input{tables}\n\n")
        f.write(t1)
        f.write("\n\n")
        f.write(t2)
        f.write("\n")

    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
