"""
Plot the best-position field generated by scripts/best_position_field.jl.
Overlays walls using the fine-resolution floor plan saved to output/floor_plan.csv
so that the visualization matches scripts/plot_coarse_heatmap.py style.
"""

import numpy as np
import matplotlib.pyplot as plt


def plot_field_heatmap(
    intensity_path="output/best_field_overall.csv",
    floor_file="output/floor_plan.csv",
    out_file="output/best_field_heatmap.png",
    title="WiFi Wave Field Intensity",
    router_pos=None,
):
    """
    Plots heatmap of wave field intensity with walls and measurement points.

    Args:
        intensity:   2D numpy array of |u|^2 values, shape (nx, ny)
        floor_file:  Path to floor plan CSV (0=wall, 1=air)
        out_file:    Output image path
        title:       Plot title
        router_pos:  Optional (x, y) tuple for router position marker
    """
    intensity = np.loadtxt("output/best_field_overall.csv", delimiter=",")
    floor = np.loadtxt(floor_file, delimiter=",")

    num_x, num_y = intensity.shape
    spacing = 10.0 / num_x
    xs = np.arange(num_x) * spacing
    ys = np.arange(num_y) * spacing

    measurement_points = [
        (1.0, 5.0, "Living Room"),
        (2.0, 1.0, "Kitchen"),
        (9.0, 1.0, "Bathroom"),
        (9.0, 7.0, "Bedroom"),
    ]

    fig, ax = plt.subplots(figsize=(12, 10))

    # Log scale brings out propagation detail across many orders of magnitude
    intensity_plot = np.log10(intensity.T + 1e-20)

    im = ax.pcolormesh(xs, ys, intensity_plot, cmap="inferno", shading="auto")

    cbar = plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04, shrink=0.7, aspect=20)
    cbar.ax.tick_params(labelsize=17)
    cbar.set_label("log₁₀(|u|²)", fontsize=17)

    # Walls
    floor_dx = 10.0 / floor.shape[0]
    floor_xs = np.arange(floor.shape[0]) * floor_dx
    floor_ys = np.arange(floor.shape[1]) * floor_dx
    ax.contour(floor_xs, floor_ys, floor.T, levels=[0.5], colors="white", linewidths=2)

    # Measurement points
    for x, y, name in measurement_points:
        ax.plot(x, y, "wo", markersize=20, markeredgecolor="black", markeredgewidth=1.5)
        ax.text(
            x,
            y + 0.3,
            name,
            ha="center",
            va="bottom",
            color="white",
            fontweight="bold",
            fontsize=15,
            bbox=dict(boxstyle="round,pad=0.3", facecolor="black", alpha=0.7),
        )

    # Optional router position
    if router_pos is not None:
        ax.plot(
            router_pos[0],
            router_pos[1],
            "*",
            color="cyan",
            markersize=18,
            markeredgecolor="black",
            markeredgewidth=1.0,
            label=f"Router ({router_pos[0]:.2f}, {router_pos[1]:.2f})",
            zorder=5,
        )
        ax.legend(fontsize=10, loc="upper left")

    ax.set_xlabel("x (m)", fontsize=17)
    ax.set_ylabel("y (m)", fontsize=17)
    ax.set_title(title, fontsize=25)
    ax.set_aspect("equal")
    ax.grid(True, alpha=0.2)

    plt.tight_layout()
    plt.savefig(out_file, dpi=300, bbox_inches="tight")
    print(f"Saved field heatmap to {out_file}")


if __name__ == "__main__":
    plot_field_heatmap()
