"""
Reads the CSV files generated by evaluate_coarse_grid.jl and creates
a heatmap visualization.
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap


def plot_wifi_heatmap(
    scores_file="output/coarse_scores.csv",
    floor_file="output/floor_plan.csv",
    spacing=0.5,
):
    """
    Creates heatmap visualization of WiFi signal strength.

    Args:
        scores_file: Path to coarse scores CSV
        floor_file: Path to floor plan CSV
        spacing: Grid spacing in meters
    """
    # Load data
    scores = np.loadtxt(scores_file, delimiter=",")
    floor = np.loadtxt(floor_file, delimiter=",")

    # Create coordinate axes
    # Julia saved scores as shape (num_x, num_y) so rows are x and columns are y.
    # Transpose the matrix for plotting (matplotlib expects array shape (len(ys), len(xs))).
    num_x, num_y = scores.shape
    xs = np.arange(num_x) * spacing
    ys = np.arange(num_y) * spacing

    # Measurement points (x, y, name)
    measurement_points = [
        (1.0, 5.0, "Living Room"),
        (2.0, 1.0, "Kitchen"),
        (9.0, 1.0, "Bathroom"),
        (9.0, 7.0, "Bedroom"),
    ]

    # Create figure
    fig, ax = plt.subplots(figsize=(12, 10))

    # Plot heatmap (transpose scores so it matches xs, ys ordering)
    im = ax.pcolormesh(xs, ys, scores.T, cmap="turbo", shading="auto")

    # Add colorbar
    cbar = plt.colorbar(im, ax=ax, label="Signal Strength")

    # Plot walls (convert floor grid to same coordinates)
    floor_dx = 10.0 / floor.shape[0]  # assuming 10m width
    floor_xs = np.arange(floor.shape[0]) * floor_dx
    floor_ys = np.arange(floor.shape[1]) * floor_dx

    ax.contour(floor_xs, floor_ys, floor.T, levels=[0.5], colors="black", linewidths=2)

    # Plot measurement points
    for x, y, name in measurement_points:
        ax.plot(x, y, "wo", markersize=10, markeredgecolor="black", markeredgewidth=1.5)
        ax.text(
            x,
            y + 0.3,
            name,
            ha="center",
            va="bottom",
            color="white",
            fontweight="bold",
            fontsize=9,
            bbox=dict(boxstyle="round,pad=0.3", facecolor="black", alpha=0.7),
        )

    # Labels and formatting
    ax.set_xlabel("X (meters)", fontsize=12)
    ax.set_ylabel("Y (meters)", fontsize=12)
    ax.set_title(
        "WiFi Signal Strength - Coarse Grid Evaluation", fontsize=14, fontweight="bold"
    )
    ax.set_aspect("equal")
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig("output/coarse_heatmap_python.png", dpi=300, bbox_inches="tight")
    print(f"Saved heatmap to output/coarse_heatmap_python.png")
    plt.show()


if __name__ == "__main__":
    plot_wifi_heatmap()
